-- CreateTable
CREATE TABLE "public"."VideoData" (
    "id" SERIAL NOT NULL,
    "comment" INTEGER,
    "typeid" INTEGER,
    "play" INTEGER,
    "pic" TEXT,
    "subtitle" TEXT,
    "description" TEXT,
    "copyright" TEXT,
    "title" TEXT,
    "review" INTEGER,
    "author" TEXT,
    "mid" INTEGER,
    "created" INTEGER,
    "length" INTEGER,
    "video_review" INTEGER,
    "aid" INTEGER,
    "bvid" TEXT,
    "hide_click" INTEGER,
    "is_pay" BOOLEAN,
    "is_union_video" BOOLEAN,
    "is_steins_gate" BOOLEAN,
    "is_live_playback" BOOLEAN,
    "is_lesson_video" BOOLEAN,
    "is_lesson_finished" BOOLEAN,
    "lesson_update_info" TEXT,
    "jump_url" TEXT,
    "meta" TEXT,
    "is_avoided" BOOLEAN,
    "season_id" INTEGER,
    "attribute" TEXT,
    "is_charging_arc" BOOLEAN,
    "elec_arc_type" TEXT,
    "elec_arc_badge" TEXT,
    "vt" BOOLEAN,
    "enable_vt" BOOLEAN,
    "vt_display" TEXT,
    "playback_position" INTEGER,
    "is_self_view" BOOLEAN,
    "view_self_type" INTEGER,

    CONSTRAINT "VideoData_pkey" PRIMARY KEY ("id")
);
